version: "3.8"
services:
  database:
    image: postgres:15-alpine
    env_file: .env
    expose:
      - 5432
    volumes:
      - pg-data:/var/lib/postgresql/data
  api:
    build: ./api
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}
      NODE_ENV: development
      PORT: 80
    depends_on:
      - database
    ports:
      - ${API_PORT}:80
    volumes:
      - .:/code
    command: sh -c "npx knex migrate:latest --knexfile=./api/knexfile.js && npx knex seed:run --knexfile=./api/knexfile.js && npm run dev:api"
  app:
    build: ./client
    environment:
      API_URL: http://api
      PORT: ${CLIENT_PORT}
    depends_on:
      - api
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - .:/code
    command: npm run dev:client
volumes:
  pg-data:
